# Generated by Django 5.2.16 on 2026-07-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="complemento",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
