# Generated by Django 5.2.16 on 2026-08-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedor", "0002_alter_fornecedor_complemento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fornecedor",
            options={
                "ordering": ["-status", "-id"],
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
    ]
