# Generated by Django 5.2.16 on 2026-08-19 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0002_empresa_deletado_por"),
        ("escola", "0002_tipoescola"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                (
                    "codigo_cadastro",
                    models.CharField(
                        max_length=255, verbose_name="código de cadastro"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="nome"),
                ),
                (
                    "status",
                    models.BooleanField(default=True, verbose_name="status"),
                ),
                (
                    "periodo_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="periodo inicial"
                    ),
                ),
                (
                    "periodo_final",
                    models.DateField(
                        blank=True, null=True, verbose_name="periodo final"
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes",
                        to="empresa.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "lote",
                "verbose_name_plural": "lotes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="LoteDRE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculo_lote",
                        to="escola.diretoriaregional",
                        verbose_name="DRE",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_dre",
                        to="lote.lote",
                        verbose_name="lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "DRE do lote",
                "verbose_name_plural": "DREs dos lotes",
                "ordering": ["id"],
            },
        ),
    ]
