# Generated by Django 5.2.17 on 2026-08-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lote", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lote",
            options={
                "ordering": ["-status", "-id"],
                "verbose_name": "lote",
                "verbose_name_plural": "lotes",
            },
        ),
    ]
