# Generated by Django 5.2.17 on 2026-08-19 20:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_tipoescola"),
        ("lote", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoteDRE",
            new_name="LoteDiretoriaRegional",
        ),
    ]
