# Generated by Django 5.2.17 on 2026-08-31 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0004_unidadeeducacional"),
        ("lote", "0002_alter_lote_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotediretoriaregional",
            name="diretoria_regional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vinculo_lote",
                to="escola.diretoriaregional",
                verbose_name="Diretoria Regional",
            ),
        ),
    ]
