# Generated by Django 5.2.17 on 2026-08-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_tipoescola"),
        ("lote", "0002_rename_lotedre_lotediretoriaregional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lotediretoriaregional",
            name="dre",
        ),
        migrations.AddField(
            model_name="lotediretoriaregional",
            name="diretoria_regional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lotes_diretorias_regionais",
                to="escola.diretoriaregional",
            ),
        ),
        migrations.AlterField(
            model_name="lotediretoriaregional",
            name="lote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vinculos_diretoria_regional",
                to="lote.lote",
                verbose_name="lote",
            ),
        ),
    ]
