services:
  backend:
    platform: linux/amd64

    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

    container_name: sme_manutencao_escolar_backend

    env_file:
      - .env

    environment:
      DJANGO_SETTINGS_MODULE: config.settings

    volumes:
      - .:/app

    command: >
      sh -c "
      python -Xfrozen_modules=off
      -m debugpy
      --listen 0.0.0.0:5678
      manage.py runserver 0.0.0.0:8002
      "

    ports:
      - "${PORT_WEB:-8002}:8002"
      - "${PORT_DEBUGPY:-5679}:5678"

    depends_on:
      postgres:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully

    restart: unless-stopped

    networks:
      - backend_network

  postgres:
    image: postgres:16

    container_name: sme_manutencao_escolar_postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

    networks:
      - backend_network

    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"

  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb

    command: keydb-server /etc/keydb/keydb.conf --appendonly yes
    env_file:
      - .env

    ports:
      - "${KEYDB_HOST_PORT:-6379}:6379"

    volumes:
      - keydb_data:/data

    healthcheck:
      test: ["CMD", "keydb-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    networks:
      - backend_network


  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery

    container_name: celery-worker

    command: >
      celery
      -A config
      worker
      --loglevel=${CELERY_LOG_LEVEL:-INFO}
      --concurrency=${CELERY_CONCURRENCY:-4}

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_healthy

    volumes:
      - .:/app

    restart: unless-stopped
    networks:
      - backend_network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery

    container_name: celery-beat

    command: >
      celery
      -A config
      beat
      --scheduler django_celery_beat.schedulers:DatabaseScheduler
      --loglevel=${CELERY_LOG_LEVEL:-INFO}

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_healthy

    volumes:
      - .:/app

    restart: unless-stopped
    networks:
      - backend_network

  flower:
    image: mher/flower

    container_name: flower

    command: >
      celery
      --broker=${CELERY_BROKER_URL}
      flower
      --port=${FLOWER_HOST_PORT:-5555}

    ports:
      - "${FLOWER_HOST_PORT:-5555}:5555"

    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_healthy

    restart: unless-stopped
    networks:
      - backend_network


  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER:  ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio-init:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: minio-init

    env_file:
      - .env

    environment:
      DJANGO_SETTINGS_MODULE: config.settings

    volumes:
      - .:/app

    command: python manage.py initialize_buckets

    depends_on:
      minio:
        condition: service_healthy

    networks:
      - backend_network
volumes:
  postgres_data:
  keydb_data:
  minio_data:

networks:
  backend_network:
    driver: bridge
