services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sme_manutencao_escolar_backend
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
    ports:
      - "8002:8000"
    restart: unless-stopped