services:
  backend:
    platform: linux/amd64

    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: sme_manutencao_escolar_backend

    env_file:
      - .env

    environment:
      DJANGO_SETTINGS_MODULE: config.settings

    volumes:
      - .:/app

    command: >
      sh -c "
      python -Xfrozen_modules=off
      -m debugpy
      --listen 0.0.0.0:5678
      manage.py runserver 0.0.0.0:8002
      "

    ports:
      - "${PORT_WEB:-8002}:8002"
      - "${PORT_DEBUGPY:-5679}:5678"

    depends_on:
      postgres:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - backend_network

  postgres:
    image: postgres:16

    container_name: sme_manutencao_escolar_postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}


    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

    networks:
      - backend_network

    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge