# Generated by Django 5.2.16 on 2026-07-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servico",
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.AlterField(
            model_name="servico",
            name="nome",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name="servico",
            table="servico",
        ),
    ]
