# Generated by Django 5.2.16 on 2026-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0002_alter_servico_options_alter_servico_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="nome",
            field=models.CharField(max_length=255),
        ),
    ]
