# Generated by Django 5.2.16 on 2026-07-23 20:23

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0003_alter_servico_nome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servico",
            options={
                "ordering": ["-id"],
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.AddIndex(
            model_name="servico",
            index=models.Index(
                fields=["status"], name="servico_status_407ce1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servico",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nome"),
                name="servico_nome_unico_case_insensitive",
            ),
        ),
    ]
