# Generated by Django 5.2.17 on 2026-08-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0004_alter_servico_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servico",
            options={
                "ordering": ["-status", "-id"],
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
    ]
