# Generated by Django 5.2.17 on 2026-08-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servico", "0006_servico_deletado_por"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="servico",
            new_name="servico_ser_status_fe3bb2_idx",
            old_name="servico_status_407ce1_idx",
        ),
        migrations.AlterModelTable(
            name="servico",
            table=None,
        ),
    ]
