# Generated by Django 5.2.17 on 2026-08-17 19:50

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "servico",
            "0007_rename_servico_status_407ce1_idx_servico_ser_status_fe3bb2_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="servico",
            name="servico_nome_unico_case_insensitive",
        ),
        migrations.AddConstraint(
            model_name="servico",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nome"),
                condition=models.Q(("deletado_em__isnull", True)),
                name="servico_nome_unico_case_insensitive",
            ),
        ),
    ]
