# Generated by Django 5.2.17 on 2026-10-06 17:52

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0007_alter_anexoresponsaveltecnico_arquivo_and_more"),
        ("lote", "0003_alter_lotediretoriaregional_diretoria_regional"),
        ("profissional", "0002_recria_documento_funcao_profissional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("situacao", models.BooleanField(default=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipes",
                        to="empresa.empresa",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipes",
                        to="lote.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipe",
                "verbose_name_plural": "Equipes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ProfissionalEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profissionais",
                        to="equipe.equipe",
                    ),
                ),
                (
                    "funcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_equipe",
                        to="profissional.funcaoprofissional",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_equipe",
                        to="profissional.profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profissional da equipe",
                "verbose_name_plural": "Profissionais da equipe",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="equipe",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nome"),
                models.F("empresa"),
                condition=models.Q(("deletado_em__isnull", True)),
                name="equipe_nome_empresa_unico",
                violation_error_message="Já existe uma equipe com este nome cadastrada para a empresa.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profissionalequipe",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deletado_em__isnull", True)),
                fields=("equipe", "profissional"),
                name="profissional_unico_por_equipe",
                violation_error_message="Não é permitido informar o mesmo profissional mais de uma vez.",
            ),
        ),
    ]
