# Generated by Django 5.2.16 on 2026-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiretoriaRegional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("abreviacao", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Diretoria Regional",
                "verbose_name_plural": "Diretorias Regionais",
                "db_table": "diretoria_regional",
            },
        ),
    ]
