# Generated by Django 5.2.17 on 2026-08-13 12:51

import uuid

import django.db.models.deletion
import django_minio_backend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("nome_original", models.CharField(max_length=255)),
                (
                    "arquivo",
                    models.FileField(
                        storage=django_minio_backend.models.MinioBackend(
                            bucket_name="sme-manutencao-escolar"
                        ),
                        upload_to="arquivos/%Y/%m/%d/",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagem", "Imagem"),
                            ("documento", "Documento"),
                            ("video", "Vídeo"),
                            ("compactado", "Compactado"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tipo_mime", models.CharField(blank=True, max_length=150)),
                ("tamanho_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
