# Generated by Django 5.2.17 on 2026-08-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_anexo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("imagem", "Imagem"),
                    ("documento", "Documento"),
                    ("compactado", "Compactado"),
                ],
                max_length=20,
            ),
        ),
    ]
