# Generated by Django 5.2.17 on 2026-08-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_anexo_tipo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiretoriaRegional",
        ),
    ]
