# Generated by Django 5.2.17 on 2026-09-17 12:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

VERBOSE_NAME_DELETADO_EM = "Deletado em"
RELATED_NAME_ATUALIZADO = "%(app_label)s_%(class)s_atualizado"
RELATED_NAME_CRIADO = "%(app_label)s_%(class)s_criado"
RELATED_NAME_DELETADO = "%(app_label)s_%(class)s_deletado"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cargo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuncaoProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name=VERBOSE_NAME_DELETADO_EM,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name=RELATED_NAME_ATUALIZADO,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcoes",
                        to="cargo.cargo",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name=RELATED_NAME_CRIADO,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name=RELATED_NAME_DELETADO,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Função do Profissional",
                "verbose_name_plural": "Funções dos Profissionais",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoFuncaoProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name=VERBOSE_NAME_DELETADO_EM,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name=RELATED_NAME_ATUALIZADO,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name=RELATED_NAME_CRIADO,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name=RELATED_NAME_DELETADO,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funcao_profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="profissional.funcaoprofissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento da Função profissional",
                "verbose_name_plural": "Documentos das Funções profissionais",
                "ordering": ["nome", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Profissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name=VERBOSE_NAME_DELETADO_EM,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("rg", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=11)),
                ("status", models.BooleanField(default=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name=RELATED_NAME_ATUALIZADO,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name=RELATED_NAME_CRIADO,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name=RELATED_NAME_DELETADO,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
                "ordering": ["-status", "-id"],
            },
        ),
        migrations.AddField(
            model_name="funcaoprofissional",
            name="profissional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funcoes",
                to="profissional.profissional",
            ),
        ),
        migrations.AddIndex(
            model_name="profissional",
            index=models.Index(
                fields=["rg"], name="profissiona_rg_6b5091_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profissional",
            index=models.Index(
                fields=["cpf"], name="profissiona_cpf_14c8ab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="profissional",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deletado_em__isnull", True)),
                fields=("cpf",),
                name="profissional_cpf_unico",
                violation_error_message="Já existe um profissional cadastrado com este CPF.",
            ),
        ),
        migrations.AddConstraint(
            model_name="profissional",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deletado_em__isnull", True)),
                fields=("rg",),
                name="profissional_rg_unico",
                violation_error_message="Já existe um profissional cadastrado com este RG.",
            ),
        ),
        migrations.AddConstraint(
            model_name="funcaoprofissional",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deletado_em__isnull", True)),
                fields=("cargo", "profissional"),
                name="funcao_profissional_cargo_unico",
                violation_error_message="Esta função já está cadastrada neste profissional.",
            ),
        ),
    ]
