"""Recria a tabela de documentos das funções profissionais."""

# Generated by Django 5.2.17 on 2026-09-17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Recria a tabela de documentos com os campos de anexo."""

    dependencies = [
        ("profissional", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentoFuncaoProfissional",
        ),
        migrations.CreateModel(
            name="DocumentoFuncaoProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("nome_original", models.CharField(max_length=255)),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="profissionais/anexos_funcoes_profissionais/"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagem", "Imagem"),
                            ("documento", "Documento"),
                            ("compactado", "Compactado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tipo_mime", models.CharField(blank=True, max_length=150)),
                ("tamanho_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "funcao_profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="profissional.funcaoprofissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento da Função profissional",
                "verbose_name_plural": "Documentos das Funções profissionais",
                "ordering": ["-id"],
            },
        ),
    ]
