"""
Django settings for apps project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import urllib.parse
from datetime import timedelta
from pathlib import Path
from typing import Any

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "dev-secret-key-not-for-production"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("true", "1")


def _parse_csv(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


ALLOWED_HOSTS = _parse_csv(os.environ.get("DJANGO_ALLOWED_HOSTS", ""))

# ``ALLOWED_HOSTS`` controla o header Host; CORS depende das origens abaixo.
CORS_ALLOW_ALL_ORIGINS = "*" in ALLOWED_HOSTS
CORS_ALLOWED_ORIGINS = [] if CORS_ALLOW_ALL_ORIGINS else ALLOWED_HOSTS

SME_API_EOL_URL = os.environ.get("SME_API_EOL_URL", "")
SME_API_EOL_TOKEN = os.environ.get("SME_API_EOL_TOKEN", "")

# Application definition
# ==========================================
# APPS DO DJANGO (Framework)
# ==========================================
APPS_DJANGO = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]
# ==========================================
# APPS DE TERCEIROS (Pacotes pip)
# ==========================================
APPS_TERCEIROS = [
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
    "django_celery_beat",
]

# ==========================================
# APPS DO PROJETO (Domínio de negócio)
# ==========================================
APPS_PROJETO = [
    "apps.core",
    "apps.usuarios",
    "apps.fornecedor",
    "apps.servico",
]

# ==========================================
# INSTALLED_APPS Final
# ==========================================
INSTALLED_APPS = APPS_DJANGO + APPS_TERCEIROS + APPS_PROJETO


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

URL_BANCO_COMAPRE = os.environ.get("URL_BANCO_POSTGRES", False)


def _parse_db_url(url: Any) -> dict:
    """Faz o parse de uma URL postgres para dict de configuração Django.

    Args:
        url: URL postgres ou valor falsy.

    Returns:
        Configuração de banco no formato esperado por ``DATABASES``.
        Quando ``url`` é vazia, devolve configuração SQLite em memória.
    """
    if not url:
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }

    if isinstance(url, bytes):
        url = url.decode("utf-8")

    parsed = urllib.parse.urlparse(str(url))
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parsed.path.lstrip("/"),
        "USER": parsed.username or "postgres",
        "PASSWORD": parsed.password or "postgres",
        "HOST": parsed.hostname or "localhost",
        "PORT": str(parsed.port or 5432),
    }


DATABASES = {
    "default": _parse_db_url(URL_BANCO_COMAPRE),
}

EXECUTANDO_TESTES = any(
    "test" in arg or "pytest" in arg for arg in sys.argv
) or os.environ.get("USE_SQLITE_TEST", "").lower() in ("1", "true")

if EXECUTANDO_TESTES:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }

print(f"----> #### Usando banco {DATABASES['default']['ENGINE']} ####")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa: E501
    },
]

AUTH_USER_MODEL = "usuarios.Usuario"
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}
# VERIFICAR ISSO SOBRE BLACK_LIST "rest_framework_simplejwt.token_blacklist"
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "SME-ManutencaoEscolar API",
    "DESCRIPTION": "Sistema de Manutenção Escolar",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": (
                    "Informe o token JWT no formato: `Bearer <token>`."
                ),
            }
        }
    },
    "SECURITY": [
        {
            "BearerAuth": [],
        }
    ],
    "SWAGGER_UI_SETTINGS": {
        "tagsSorter": "alpha",
        "operationsSorter": "alpha",
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
}

#
KEYDB_HOST = os.environ.get("KEYDB_HOST", "")
KEYDB_PORT = os.environ.get("KEYDB_PORT", "")
KEYDB_HOST_PORT = os.environ.get("KEYDB_HOST_PORT", "")
FLOWER_PORT = os.environ.get("FLOWER_PORT", "")
FLOWER_HOST_PORT = os.environ.get("FLOWER_HOST_PORT", "")

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "")

CELERY_CONCURRENCY = os.environ.get("CELERY_BROKER_URL", "")
CELERY_LOG_LEVEL = os.environ.get("CELERY_LOG_LEVEL", "")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = USE_TZ
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 0))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "")

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
