# Generated by Django 5.2.16 on 2026-07-23 11:26

from django.db import migrations

CARGOS = {
    "UE": [
        (3360, "DIRETOR DE ESCOLA"),
    ],
    "DRE": [
        (3000, "DIRETOR REGIONAL DE EDUCAÇÃO"),
    ],
    "SME": [
        (513, "ASSISTENTE TECNICO I"),
        (2640, "ASSISTENTE TECNICO DE EDUCACAO I"),
        (3042, "ASSISTENTE TECNICO EDUCACIONAL"),
    ],
    "EMPRESA": [
        (2127, "ENGENHEIRO I"),
        (2135, "ENGENHEIRO II"),
        (2143, "ENGENHEIRO III"),
        (2151, "ENGENHEIRO IV"),
    ],
}


def popular_cargos_eol(apps, schema_editor):
    cargo_eol = apps.get_model("usuarios", "CargoEOL")

    objetos = [
        cargo_eol(
            codigo=codigo,
            nome=nome,
            perfil=perfil,
        )
        for perfil, cargos in CARGOS.items()
        for codigo, nome in cargos
    ]

    cargo_eol.objects.bulk_create(
        objetos,
        ignore_conflicts=True,
    )


def remover_cargos_eol(apps, schema_editor):
    cargo_eol = apps.get_model("usuarios", "CargoEOL")

    codigos = [codigo for cargos in CARGOS.values() for codigo, _ in cargos]

    cargo_eol.objects.filter(codigo__in=codigos).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            popular_cargos_eol,
            remover_cargos_eol,
        ),
    ]
