# Generated by Django 5.2.17 on 2026-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_popular_cargos_eol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoeol",
            name="perfil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UE", "Diretor Unidade Educarional"),
                    ("DRE", "Diretoria Regional de Educação"),
                    ("SME", "SME / GME"),
                    ("EMPRESA", "Empresa"),
                ],
                max_length=70,
                null=True,
            ),
        ),
    ]
