# Generated by Django 5.2.17 on 2026-08-18 14:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoEscola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "codigo_eol",
                    models.PositiveIntegerField(
                        help_text="Código identificador do tipo de escola no sistema EOL.",
                        unique=True,
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        help_text="Sigla que identifica o tipo de escolar.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de unidade",
                "verbose_name_plural": "Tipos de unidade",
                "ordering": ("sigla",),
            },
        ),
    ]
