# Generated by Django 5.2.17 on 2026-08-19 15:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_tipoescola"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subprefeitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "codigo_eol",
                    models.CharField(
                        help_text="Código identificador da Subprefeitura no sistema EOL.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da Subprefeitura.", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Subprefeitura",
                "verbose_name_plural": "Subprefeituras",
                "ordering": ("nome",),
            },
        ),
    ]
