# Generated by Django 5.2.17 on 2026-08-19 20:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0003_subprefeitura"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unidadeeducacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "codigo_eol",
                    models.CharField(
                        help_text="Código identificador da escola no sistema EOL.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da escola.", max_length=255
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "diretoria_regional",
                    models.ForeignKey(
                        help_text="Diretoria Regional de Educação da escola.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escolas",
                        to="escola.diretoriaregional",
                    ),
                ),
                (
                    "subprefeitura",
                    models.ForeignKey(
                        help_text="Subprefeitura onde a escola está localizada.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escolas",
                        to="escola.subprefeitura",
                    ),
                ),
                (
                    "tipo_escola",
                    models.ForeignKey(
                        help_text="Tipo da unidade escolar.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escolas",
                        to="escola.tipoescola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escola",
                "verbose_name_plural": "Escolas",
                "ordering": ("nome",),
            },
        ),
    ]
