# Generated by Django 5.2.17 on 2026-08-24 16:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0004_unidadeeducacional"),
        ("usuarios", "0002_popular_cargos_eol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsavelUnidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                (
                    "registro_funcional",
                    models.CharField(
                        help_text="Registro funcional do servidor.",
                        max_length=7,
                        unique=True,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do servidor.", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="E-mail institucional do servidor.",
                        max_length=254,
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Telefone de contato do servidor.",
                        max_length=20,
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Celular de contato do servidor.",
                        max_length=20,
                    ),
                ),
                ("esta_afastado", models.BooleanField(default=False)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsável da Unidade",
                "verbose_name_plural": "Responsáveis das Unidades",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="HistoricoResponsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o responsável está atualmente vinculado.",
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        help_text="Cargo exercido pelo responsável na unidade.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historicos_responsaveis",
                        to="usuarios.cargoeol",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unidade_educacional",
                    models.ForeignKey(
                        help_text="Unidade educacional onde o responsável exerce a função.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_responsaveis",
                        to="escola.unidadeeducacional",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        help_text="Responsável vinculado à unidade educacional.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historicos_unidade",
                        to="escola.responsavelunidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Responsável da Unidade",
                "verbose_name_plural": "Históricos de Responsáveis das Unidades",
                "ordering": ("-atualizado_em",),
                "indexes": [
                    models.Index(
                        fields=["unidade_educacional", "ativo"],
                        name="hist_resp_unidade_ativo_idx",
                    ),
                    models.Index(
                        fields=["responsavel", "ativo"],
                        name="hist_resp_resp_ativo_idx",
                    ),
                    models.Index(
                        fields=["cargo", "ativo"],
                        name="hist_resp_cargo_ativo_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("responsavel", "unidade_educacional", "cargo"),
                        name="unique_resp_unidade_cargo",
                    )
                ],
            },
        ),
    ]
