# Generated by Django 5.2.17 on 2026-08-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0005_responsavelunidade_historicoresponsavel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diretoriaregional",
            options={
                "ordering": ("nome",),
                "verbose_name": "Diretoria Regional",
                "verbose_name_plural": "Diretorias Regionais",
            },
        ),
    ]
