# Generated by Django 5.2.17 on 2026-08-26 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0006_alter_diretoriaregional_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subprefeitura",
            name="diretoria_regional",
            field=models.ForeignKey(
                blank=True,
                help_text="Diretoria Regional responsável pela Subprefeitura.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subprefeituras",
                to="escola.diretoriaregional",
                verbose_name="Diretoria Regional",
            ),
        ),
    ]
