# Generated by Django 5.2.17 on 2026-08-27 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0007_subprefeitura_diretoria_regional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadeeducacional",
            name="subprefeitura",
            field=models.ForeignKey(
                blank=True,
                help_text="Subprefeitura onde a escola está localizada.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="escolas",
                to="escola.subprefeitura",
            ),
        ),
    ]
