# Generated by Django 5.2.17 on 2026-08-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0008_alter_unidadeeducacional_subprefeitura"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subprefeitura",
            name="diretoria_regional",
        ),
        migrations.AddField(
            model_name="subprefeitura",
            name="diretorias_regionais",
            field=models.ManyToManyField(
                blank=True,
                help_text="Diretorias Regionais responsável pela Subprefeitura.",
                related_name="subprefeituras",
                to="escola.diretoriaregional",
                verbose_name="Diretoria Regional",
            ),
        ),
    ]
