# Generated by Django 5.2.17 on 2026-08-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0009_remove_subprefeitura_diretoria_regional_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unidadeeducacional",
            options={
                "ordering": ("-status", "nome"),
                "verbose_name": "Escola",
                "verbose_name_plural": "Escolas",
            },
        ),
    ]
