# Generated by Django 5.2.17 on 2026-08-31 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0010_alter_unidadeeducacional_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosUnidadeEducacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "telefone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "logradouro",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "numero",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "cep",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "municipio",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("uf", models.CharField(blank=True, default="", max_length=2)),
                (
                    "unidade_educacional",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados",
                        to="escola.unidadeeducacional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados da Unidade Educacional",
                "verbose_name_plural": "Dados das Unidades Educacionais",
            },
        ),
    ]
