# Generated by Django 5.2.17 on 2026-09-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0011_dadosunidadeeducacional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsavelunidade",
            name="registro_funcional",
            field=models.CharField(
                help_text="Registro funcional do servidor.",
                max_length=11,
                unique=True,
            ),
        ),
    ]
