# Generated by Django 5.2.17 on 2026-09-25 15:54

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def criar_uuid_dados_unidade_educacional(apps, schema_editor):
    dados_unidade = apps.get_model(
        "escola",
        "DadosUnidadeEducacional",
    )

    for registro in dados_unidade.objects.all():
        registro.uuid = uuid.uuid4()
        registro.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0013_unidadeeducacional_atualizado_em_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dadosunidadeeducacional",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="dadosunidadeeducacional",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_atualizado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dadosunidadeeducacional",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dadosunidadeeducacional",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_criado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dadosunidadeeducacional",
            name="deletado_em",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Deletado em"
            ),
        ),
        migrations.AddField(
            model_name="dadosunidadeeducacional",
            name="deletado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deletado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dadosunidadeeducacional",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(
            criar_uuid_dados_unidade_educacional,
            migrations.RunPython.noop,
        ),
    ]
