# Generated by Django 5.2.17 on 2026-09-09 17:31

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("exige_documento", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=True)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["-status", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="cargo.cargo",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do cargo",
                "verbose_name_plural": "Documentos dos cargos",
                "ordering": ["nome", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["status"], name="cargo_cargo_status_306572_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["exige_documento"],
                name="cargo_cargo_exige_d_eef7d3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cargo",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nome"),
                condition=models.Q(("deletado_em__isnull", True)),
                name="cargo_nome_unico_case_insensitive",
            ),
        ),
        migrations.AddIndex(
            model_name="documentocargo",
            index=models.Index(
                fields=["cargo"], name="cargo_docum_cargo_i_cdee08_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentocargo",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nome"),
                models.F("cargo"),
                condition=models.Q(("deletado_em__isnull", True)),
                name="documento_cargo_nome_unico",
            ),
        ),
    ]
