# Generated by Django 5.2.17 on 2026-09-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cargo",
            name="cargo_cargo_status_306572_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargo",
            name="cargo_cargo_exige_d_eef7d3_idx",
        ),
    ]
