# Generated by Django 5.2.17 on 2026-08-07 17:39

import re
import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "cnpj",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CNPJ inválido: deve ter 14 posições, sendo as 12 primeiras alfanuméricas (0-9, A-Z) e as 2 últimas numéricas.",
                                regex=re.compile("^[A-Z0-9]{12}\\d{2}$"),
                            )
                        ],
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("razao_social", models.CharField(max_length=255)),
                (
                    "link_rastreio",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Link inválido: deve ser uma URL válida.",
                                regex=re.compile("^https?://[^\\s]+$"),
                            )
                        ],
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Este campo deve conter apenas dígitos numéricos.",
                                regex="^\\d+$",
                            )
                        ],
                    ),
                ),
                ("logradouro", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=30)),
                (
                    "complemento",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("cidade", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["-status", "-id"],
                "indexes": [
                    models.Index(
                        fields=["cnpj"], name="empresa_emp_cnpj_84a215_idx"
                    ),
                    models.Index(
                        fields=["status"], name="empresa_emp_status_cc141b_idx"
                    ),
                ],
            },
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS fornecedor;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
