# Generated by Django 5.2.17 on 2026-08-19 19:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_empresa_deletado_por"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsavelTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preposto", "Preposto"),
                            ("engenheiro_civil", "Engenheiro Civil"),
                            (
                                "engenheiro_eletricista",
                                "Engenheiro Eletricista",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "numero_crea",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "numero_art",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("email", models.EmailField(max_length=255)),
                (
                    "telefone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsaveis_tecnicos",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsável Técnico",
                "verbose_name_plural": "Responsáveis Técnicos",
                "ordering": ["-id"],
            },
        ),
    ]
