# Generated by Django 5.2.17 on 2026-08-19 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_responsaveltecnico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsaveltecnico",
            name="telefone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Este campo deve conter apenas dígitos numéricos.",
                        regex="^\\d+$",
                    )
                ],
            ),
        ),
    ]
