# Generated by Django 5.2.17 on 2026-08-24 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0004_alter_responsaveltecnico_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsaveltecnico",
            name="telefone",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Este campo deve conter apenas dígitos numéricos.",
                        regex="^\\d+$",
                    )
                ],
            ),
        ),
    ]
