# Generated by Django 5.2.17 on 2026-09-02 20:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0005_alter_responsaveltecnico_telefone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnexoResponsavelTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("nome", models.CharField(max_length=1000)),
                (
                    "arquivo_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "arquivo",
                    models.FileField(
                        storage=apps.core.storage.get_private_storage,
                        upload_to="anexos_responsaveis_tecnicos/",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel_tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="empresa.responsaveltecnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo do Responsável Técnico",
                "verbose_name_plural": "Anexos dos Responsáveis Técnicos",
                "ordering": ["-id"],
            },
        ),
    ]
