# Generated by Django 5.2.17 on 2026-09-03 21:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0005_alter_responsaveltecnico_telefone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnexoResponsavelTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Deletado em",
                    ),
                ),
                ("nome_original", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("imagem", "Imagem"),
                            ("documento", "Documento"),
                            ("compactado", "Compactado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tipo_mime", models.CharField(blank=True, max_length=150)),
                ("tamanho_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "arquivo",
                    models.FileField(
                        storage=apps.core.storage.get_private_storage,
                        upload_to="empresas/anexos_responsaveis_tecnicos/",
                    ),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deletado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsavel_tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="empresa.responsaveltecnico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo do Responsável Técnico",
                "verbose_name_plural": "Anexos dos Responsáveis Técnicos",
                "ordering": ["-id"],
            },
        ),
    ]
