# Generated by Django 5.2.17 on 2026-09-08 18:46

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0006_anexoresponsaveltecnico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexoresponsaveltecnico",
            name="arquivo",
            field=models.FileField(
                upload_to="empresas/anexos_responsaveis_tecnicos/"
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="cnpj",
            field=models.CharField(
                max_length=14,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CNPJ inválido: deve ter 14 posições, sendo as 12 primeiras alfanuméricas (0-9, A-Z) e as 2 últimas numéricas.",
                        regex=re.compile("^[A-Z0-9]{12}\\d{2}$"),
                    )
                ],
            ),
        ),
    ]
